const URL = {
    "Arianespace": "https://www.arianespace.com/",
    "Blue Origin": "https://www.blueorigin.com/",
    "CASC": "https://www.spacechina.com/",
    "China Great Wall Industry Corporation": "http://www.cgwic.com/",
    "Eurockot Launch Services": "https://www.eurockot.com/",
    "ExPace": "http://www.expace.com.cn/",
    "Firefly": "https://fireflyspace.com/",
    "Galactic Energy": "https://en.geespace.com/",
    "Gilmour Space": "https://www.gspacetech.com/",
    "ISRO": "https://www.isro.gov.in/",
    "Iranian Space Agency": "https://isa.ir/",
    "JAXA": "https://global.jaxa.jp/",
    "Korean Aerospace Research Institute": "https://www.kari.re.kr/",
    "LandSpace": "http://www.landspace.com/",
    "Mitsubishi Heavy Industries": "https://www.mhi.com/",
    "NASA": "https://www.nasa.gov/",
    "North Korea (NADA)": "No official website",
    "Northrop Grumman": "https://www.northropgrumman.com/",
    "OneSpace": "http://www.onespacechina.com/",
    "Orbex": "https://orbex.space/",
    "PLD Space": "https://pldspace.com/",
    "Relativity Space": "https://www.relativityspace.com/",
    "Rocket Lab": "https://www.rocketlabusa.com/",
    "RocketStar": "https://www.rocketstar.nyc/",
    "Roscosmos": "https://www.roscosmos.ru/",
    "Sierra Nevada Corporation": "https://www.sncorp.com/",
    "Skyrora": "https://www.skyrora.com/",
    "SpaceX": "https://www.spacex.com/",
    "Spaceflight Inc.": "https://spaceflight.com/",
    "SSLV (ISRO Small Satellite Launch Vehicle)": "https://www.isro.gov.in/Launchers/SSLV.html",
    "United Launch Alliance (ULA)": "https://www.ulalaunch.com/",
    "Virgin Galactic": "https://www.virgingalactic.com/",
    "Virgin Orbit": "https://virginorbit.com/",
  };
  